services:
  - type: web
    name: SACHIN TXT DIRECT
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/Sachin9352/TUSHAR-DRM-TXT-UPLOADER
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      #- key: WEBHOOK
        #sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
